theme: jekyll-theme-cayman

title: MA-7 Digital Marketing
description: MA-7 Digital Marketing Website!

logo: https://raw.githubusercontent.com/AlwaysLearning55/AlwaysLearning55.github.io/master/ma7logo.png
#show_downloads: [false]
#google_analytics: UA-176717910-1
