theme: jekyll-theme-minimal

title: AlwaysLearning's portifolio!
description: This is a website where I will host any code I work on during my graduation and will keep my contact info for future job references. Have fun exploring!

logo: https://raw.githubusercontent.com/AlwaysLearning55/AlwaysLearning55.github.io/master/test_image.png
#show_downloads: [false]
google_analytics: UA-176717910-1
